### ISSUE TITLE
Avalanche CLI fails to interact with Ledger Device after App update to v0.8.4

### ISSUE THREAD

**Issue by saan099** [ava-labs/ledger-avalanche#326] opened 2024-09-19 23:33 UTC
**Specifications**:
Ledger Device:- Ledger nano S+
OS:- Ubuntu 22.04
Avalanche Ledger App Version:- 0.8.4
Avalanche CLI version:- v1.7.1(also tested with older v1.3.5)

**Description**
We are using 4 Ledger nano S+ devices onto for our purposes on the Ubuntu machines and this issue seems has been encountered with the three of the devices that we've tried on so far. Accessing the ledger wallet using Avalanche CLI fails with the following error:-

`$ avalanche key list --ledger 0 --mainnet`
`Error: LedgerHID device (idx 0) not found. Ledger LOCKED OR Other Program/Web Browser may have control of device.`

The device is unlocked and the avalanche app is in ready state during this command's execution. This issue has only started coming since the firmware of the device has been updated `1.1.2` and avalanche app has been updated from version `0.7.3` to `0.8.4`. The same 3 devices which function with these updated softwares seem to have all developed the issue, while the one device that's still running the older firmware and avalanche ledger app continues to work fine for the command above. We also made sure that the device is not connected to ledger live app(which was closed at the time) and also any browser window(wallet).

**Hints & Observations**:

- We've tested two CLI versions, latest - 1.7.1 and 1.3.5, the issue exists with both of them for the 3 updated devices and both versions work fine with the non-updated device.
- We've seen that the ledger device after the upgraded firmware & avalanche ledger app, continues to connect perfectly fine with the core wallet extension, as well as with the ledger live app.
- We've been able to produce the above issue on two separate Ubuntu 22.04 machines ensuring the device is not connected anywhere else, also rebooting the machines and trying to access with avalanche CLI as the first thing when it reboots again.
- We do observe that the `ledger-go` library in the codebase of both avalanche CLI and ledger-avalanche code base have a version of `v0.14.3` while there is a later version available is `v0.15`.
- We can also confirm that if the avalanche app is intentionally kept closed(not in 'Avalanche ready' state), the error thrown by the CLI is `Error: [APDU_CODE_APP_NOT_OPEN] Ledger Connected but Chain Specific App Not Open` which means that avalanche CLI does recognise the device and also the fact that it is unlocked.

**Comment by saan099** [comment] 2024-09-20 13:11
Also, building avalanche CLI manually from source as the link suggests here doesn't work as suggested [here](https://github.com/ava-labs/ledger-avalanche/issues/320#issuecomment-2249254220). We've tried to build it as it is from main branch, then updating with the latest release of ledger-avalanche package(v0.8.4), and also taking the main branch of ledger-avalanche package and using that within build of avalanche CLI. We get the same problem.

**Comment by sourajyoti-gupta** [comment] 2024-09-24 07:07
Hi @saan099 , Ledger firmware updates to Nano S+ devices recently to 1.1.2 is highly susceptible to have caused this error as we've observed this in the past as well. A few things I would like to suggest:
1. We recently merged few dependencies with the `hw-app-lib` (libraries) and it might work now for you. Have you tried very recently again?
2. The app has a new release `v0.8.5`, please update your device and try again.
3. Also you to erase your device cache of old Firmware upgrade from the browser you're connecting. An installation of fresh Ledger Nano S+ with updated firmware will do the trick.
4. Make sure your device is not connected to any other wallet, app, swap/bridge websites, etc. while you're connecting it to Ledger Live.

**Comment by saan099** [comment] 2024-09-25 18:32
Hi @sourajyoti-gupta , Thanks for the information. 

I've built the avalanche-cli again with the new updated version of ledger-avalanche. But that doesn't help. It gives the same issue. Following mechanism was used to do so,
`$ go get github.com/ava-labs/ledger-avalanche/go@latest`
`$ go mod tidy`
`$ go build -o avalanche-cli`

For using updated ledger-avalanche app within the device. I see that the ledger live app still shows the latest available release to be `0.8.4`. I see that the repo however has the new marked release of `0.8.5`. Will it be some time before we see it on the ledger live app for updatting the app? I see the disclaimer in readme of course which discourages using the release directly on the ledger device.

**Comment by emmanuelm41** [comment] 2024-10-09 18:40
@saan099 the issue should be solved now. Feel free to close it once you check it works again.

**Comment by ainhoa-a** [comment] 2024-10-09 18:43
We’ve identified the root cause and implemented a solution.  As initially suspected, the issue originated from the firmware upgrade to Ledger version 1.1.2, which impacted the ledger-go package responsible for device connection. The fix involved adjusting the HID product ID. We also upgraded other dependencies. Notably, the issue only affected Linux, not macOS or Windows.

A new release will be published shortly. Apps that use this library (https://github.com/ava-labs/ledger-avalanche/tree/main/go) as a dependency will need to update it.

**Comment by sourajyoti-gupta** [comment] 2024-11-05 16:51
Hi @saan099 , can you mark this issue closed? Thanks!

**Closed** 2024-12-04 16:17 UTC
